#�����˿�
server:
  port: 8082
#ע����������
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
#Ӧ������
spring:
  application:
    name: user-center
feign:
  hystrix:
    enabled: true